services:
  - type: web
    name: irbah-cash-dz-bot
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: API_TOKEN
        value: "6150770166:AAHZr2GfSv5h_oXvK7Wcwksml5KGlixxxxxxxxx"
    autoDeploy: true
